### PR TITLE
gym environment initial implementation

### PR DESCRIPTION
**Pull request by ryanhoque**
Hi Daniel, haven't tested this yet but see if these changes make sense to you

### CODE REVIEW

**Comment by DanielTakeshi** [comment]
Great!!  I have budgeted time Monday afternoon to work and check this.

**Comment by DanielTakeshi** [comment]
Sorry, had a ton of other stuff come up and there were networking issues with hermes1 when I finally was able to come to lab. I'll be busy Wed/Thursday but have allocated all day Friday for cloth sim

**Comment by ryanhoque** [comment]
No worries, in the meantime I'll work on testing it and then seeing if I can learn anything with RL algorithms

**Comment by DanielTakeshi** [comment]
Thanks for fixing tabs and spaces -- for our code can we use the convention that 4 spaces = 1 tab throughout?

**Comment by DanielTakeshi** [comment]
Also the code shouldn't use any sys.path.append calls that are dependent on the machine -- this should be a pip package that we can collectively install. Eventually we'll move it to BerkeleyAutomation repos to start fresh

**Comment by DanielTakeshi** [comment]
Thanks for the work!

**Pull request merged**
